title: The Refuge
description: "The Refuge: Empowering Lives and Bridging Communities"
owner_name: Armaghan Zarak
github_username: Armaghan-Z
baseurl: "/refuge"
url: "https://armaghan-z.github.io"
google_analytics:

# Navigation
header_pages:
  - navigation/resources.md
  - navigation/employment.md
  - navigation/community.md
  - navigation/about.md
  - navigation/contact.md

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

navigation:
  - title: Home
    url: /
  - title: Resources
    url: /navigation/resources
  - title: Community
    url: /navigation/community
  - title: Employment
    url: /navigation/employment
  - title: About
    url: /navigation/about
  - title: Contact
    url: /navigation/contact