title: The Refuge 
description: "The Refuge: Empowering Lives and Bridging Communities."
owner_name: Armaghan Zarak
github_username: Armaghan-Z
github_repo: "refuge" 
baseurl: "/refuge"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/resources.md
  - employment.md
  - community.md
  - about.md
  - contact.md