title: The Refuge
description: "The Refuge: Empowering Lives and Bridging Communities"
owner_name: Armaghan Zarak
github_username: Armaghan-Z
baseurl: "/refuge"
url: "https://armaghan-z.github.io"
google_analytics:

# Theme
theme: jekyll-theme-cayman

# Navigation
header_pages:
  - navigation/resources.md
  - employment.md
  - community.md
  - about.md
  - contact.md

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

navigation:
  - title: Home
    url: /
  - title: Resources
    url: /navigation/resources
  - title: Community
    url: /navigation/community
  - title: Employment
    url: /navigation/employment
  - title: About
    url: /navigation/about
  - title: Contact
    url: /navigation/contact